app: mc-bounty-processor
org: ryanallen

service: mc-bounty-processor

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  role: arn:aws:iam::425071954352:role/service-role/mc-microservice-role
  environment:
    LOGGER_ENABLED: true
    TABLE_BOUNTIES:
      Ref:
        - BountiesDatabase

functions:
  mc-bounty-processor:
    handler: src/index.handler
    events:
      - httpApi:
          path: /bounty
          method: post
    environment:
      TABLE_BOUNTIES: bounties
      LOGGER_ENABLED: true
      SERVICE_WALLET_URL: ${env:SERVICE_WALLET_URL}
      DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}
      DISCORD_WEBHOOK_THUMBNAIL_URL: ${env:DISCORD_WEBHOOK_THUMBNAIL_URL}

resources:
  Resources:
    BountiesDatabase:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "BountyId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "BountyId"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"