app: mc-bounty-processor
org: ryanallen

service: mc-bounty-processor

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  role: arn:aws:iam::425071954352:role/service-role/mc-microservice-role
  environment:
    TABLE_BOUNTIES: bounties
    LOGGER_ENABLED: true

custom:
  serverlessSsmFetch:
    SERVICE_WALLET_URL: /mc-bounty-processor/${opt:stage}/SERVICE_WALLET_URL
    DISCORD_WEBHOOK_URL: /mc-bounty-processor/${opt:stage}/DISCORD_WEBHOOK_URL
    DISCORD_WEBHOOK_THUMBNAIL_URL: /mc-bounty-processor/${opt:stage}/DISCORD_WEBHOOK_THUMBNAIL_URL

functions:
  mc-bounty-processor:
    handler: src/index.handler
    events:
      - httpApi:
          path: /user
          method: get
    environment:
      TABLE_BOUNTIES: bounties
      LOGGER_ENABLED: true
plugins:
  - serverless-ssm-fetch